<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\ProjectTemplateDotnet.Infrastructure.CrossCutting\ProjectTemplateDotnet.Infrastructure.CrossCutting.csproj" />
    <ProjectReference Include="..\..\Core\ProjectTemplateDotnet.Application\ProjectTemplateDotnet.Application.csproj" />
  </ItemGroup>

</Project>